#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-mongodb

check_container_initialized
check_service_initialized init

cmd="mongod --bind_ip 0.0.0.0 \
            --port $DB_PORT \
            --storageEngine $STORAGE_ENGINE \
            --timeStampFormat iso8601-local"

if var_true $ENABLE_AUTHENTICATION ; then
    cmd="$cmd \ --auth"
fi
 
if var_false $ENABLE_JOURNALING ; then
    cmd="$cmd \ --nojournal"
fi

if var_true $ENABLE_LOGS ; then
    chmod -R 755 /etc/logrotate.d/mongodb.conf
    cmd="$cmd --logpath /data/logs/mongodb.log --logappend"
fi

if var_true $ENABLE_REPLICATION ; then
    cmd="$cmd --replSet $REPLICATION_NAME"
fi 

if [ "$MAX_CONNECTIONS" != "" ]; then 
    cmd="$cmd --maxConns $MAX_CONNECTIONS"
fi

if [ "$OPLOG_SIZE" != "" ]; then
    cmd="$cmd --oplogSize $OPLOG_SIZE"
fi

if [ -n "$ADDITIONAL_PARAMETERS" ]; then
    cmd="$cmd $ADDITIONAL_PARAMETERS"
fi

liftoff

print_info "Starting MongoDB ${MONGO_VERSION}"
exec sudo -u mongodb $cmd
