#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="mongodb"

if [ ! -f "/data/db/.mongodb_init" ]; then
	if [ "$DB_NAME" != "admin" ]; then
		sanity_var DB_USER "Database User"
		sanity_var DB_PASS "Database Pass"
	fi
fi

mkdir -p /data/db
chown -R mongodb /data/db

if var_true $ENABLE_LOGS ; then
    mkdir -p /data/logs
    cat <<EOF > /etc/logrotate.d/mongodb.conf
/data/logs/*.log {
daily
ifempty
rotate 7
missingok
compress
dateext
copytruncate
}
EOF
fi

liftoff
