#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service both 10-mongo
PROCESS_NAME=mongo
check_container_initialized
check_service_initialized init

print_start "Starting MongoDB ${MONGO_VERSION/r/}"
s6-setuidgid mongo mongod ${mongocmd}
